ALTER TABLE `Etat`
  ADD COLUMN `CreateDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN `UpdateDate` DATETIME(3) NULL;

ALTER TABLE `Type`
  ADD COLUMN `CreateDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN `UpdateDate` DATETIME(3) NULL;

ALTER TABLE `Marque`
  ADD COLUMN `CreateDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN `UpdateDate` DATETIME(3) NULL;

ALTER TABLE `Carburant`
  ADD COLUMN `CreateDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN `UpdateDate` DATETIME(3) NULL;

ALTER TABLE `Vehicule`
  ADD COLUMN `CreateDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE `Relever`
  ADD COLUMN `CreateDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE `CategorieEntretien`
  ADD COLUMN `CreateDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN `UpdateDate` DATETIME(3) NULL;

ALTER TABLE `EntretienType`
  ADD COLUMN `CreateDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN `UpdateDate` DATETIME(3) NULL;

ALTER TABLE `Grade`
  ADD COLUMN `CreateDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN `UpdateDate` DATETIME(3) NULL;

ALTER TABLE `Utilisateur`
  ADD COLUMN `CreateDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN `UpdateDate` DATETIME(3) NULL;
